#!/bin/sh

#shellcheck disable=SC1091
. /srv/env

show_usage() {
    echo "Usage: create REPO_NAME"
}

if [ $# -ne 1 ]
then
    show_usage
    exit 1
fi

echo "Creating repo $1"
GIT_REPO="${REPO_ROOT}/$USER/$1"
if [ -d "$GIT_REPO" ]; then
    echo "Already exists, skipped !"
    exit 1
fi
git init --bare "$GIT_REPO"


echo "You can now clone it :"
echo "git clone ssh://${USER}@$EXTERNAL_HOSTNAME:$EXTERNAL_PORT${GIT_REPO}"
