#!/bin/sh

#shellcheck disable=SC1091
. /srv/env

show_usage() {
    echo "Usage: show REPO_NAME"
}

if [ $# -ne 1 ]
then
    show_usage
    exit 1
fi

GIT_REPO="${REPO_ROOT}/$USER/$1"
if [ -d "$GIT_REPO" ]; then
    echo "git clone ssh://${USER}@$EXTERNAL_HOSTNAME:$EXTERNAL_PORT${GIT_REPO}"
else
    echo "Repo does not exists"
fi
